<a href="https://colab.research.google.com/github/hungpx2008/AIO-Exercise/blob/Feature%2FExercise-activate-funtion/Excercise3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
#Viết class và cài phương thức softmax.
import torch
import torch.nn as nn

In [56]:
data = torch.Tensor([1,2,3])
data

tensor([1., 2., 3.])

In [57]:
softmax_function=nn.Softmax(dim=0)
output=softmax_function(data)
output

tensor([0.0900, 0.2447, 0.6652])

In [97]:
class MySoftmax(nn.Module):
  def __init__(self):
    super().__init__()
  def forward(self,x):
    x_exp=torch.exp(x)
    total=x_exp.sum(0,keepdim=True)
    return x_exp/total
my_softmax=MySoftmax()
output=my_softmax(torch.Tensor([1, 2, 3000000000])
)
output

tensor([0., 0., nan])

In [98]:
class StableSoftmax(nn.Module):
  def __init__(self):
    super().__init__()
  def forward(self,x):
    c = torch.max(x,dim=0)
    x_exp=torch.exp(x-c.values)
    total=x_exp.sum(0,keepdim=True)
    return x_exp/total
stable_softmax=StableSoftmax()
output=stable_softmax(torch.Tensor([1,2,3]))
output


tensor([0.0900, 0.2447, 0.6652])

In [60]:
#2
from abc import ABC, abstractmethod


In [61]:
class Person(ABC):
  def  __init__(self,name,yob):
    self.name=name
    self.yob=yob
  @abstractmethod
  def describe(self):
    print(f"I am {self.name}")
class Student(Person):
  def __init__(self,name,yob,grade):
    super().__init__(name,yob)
    self.__grade=grade
  def describe(self):
    print(f"I am: {self.name} and I am : {self.yob} years old- Grade: {self.__grade}")


In [62]:
student1=Student("Nam",2001,10)
student1.describe()

I am: Nam and I am : 2001 years old- Grade: 10


In [63]:
class Doctor(Person):
  def __init__(self,name,yob,specialist):
    super().__init__(name,yob)
    self.__specialist=specialist
  def describe(self):
    print(f"I am: {self.name} and I am : {self.yob} years old- specialist: {self.__specialist}")

In [64]:
doctor1=Doctor("Nam",2001,"Medicine")
doctor2=Doctor("hung",2002,"Medicine2")
doctor1.describe()

I am: Nam and I am : 2001 years old- specialist: Medicine


In [65]:
class Teacher(Person):
  def __init__(self,name,yob,subject):
    super().__init__(name,yob)
    self.__subject=subject
  def describe(self):
    print(f"I am: {self.name} and I am : {self.yob} years old- subject: {self.__subject}")

In [71]:
class Ward:
    def __init__(self,name):
        self.__name=name
        self.__list_people=[]
    def add_person(self,person):
        self.__list_people.append(person)
    def remove_person(self,person):
        self.__list_people.remove(person)
    def describe(self):
        print(f"Ward: {self.__name}")
        for person in self.__list_people:
            person.describe()
    def list_people(self):
        return self.__list_people
    def count_doctor(self):
        count=0
        for person in self.__list_people:
            if isinstance(person,Doctor):
                count+=1
        return count
    def sort_yob(self):
        return sorted(self.__list_people,key=lambda x:x.yob)
    def compute_average(self):
        total=0
        count=0
        for person in self.__list_people:
            if isinstance(person,Teacher):
              count +=1
              total+=person.yob
        return total/len(self.__list_people)

In [72]:
ward1=Ward("Ward1")
ward1.add_person(doctor1)
ward1.add_person(doctor2)
ward1.add_person(student1)
ward1.describe()
ward1.list_people()
ward1.count_doctor()
ward1.sort_yob()

Ward: Ward1
I am: Nam and I am : 2001 years old- specialist: Medicine
I am: hung and I am : 2002 years old- specialist: Medicine2
I am: Nam and I am : 2001 years old- Grade: 10


In [80]:
#3Thực hiện xây dựng class Stack với các phương thức
class MyStack:
  def __init__(self,capacity):
    self.__capacity=capacity
    self.__list=[]
  def is_empty(self):
    return len(self.__list)==0
  def is_full(self):
    return len(self.__list)==self.__capacity
  def push(self,item):
    if not self.is_full():
      raise Exception("Stack is full")
    else:
      self.__list.append(item)
  def pop(self):
    if not self.is_empty():
      return self.__list.pop()
  def top(self):
    if not self.is_empty():
      return self.__list[-1]


In [79]:
my_stack=MyStack(3)
my_stack.is_empty()

True

In [ ]:
#4.Thực hiện xây dựng class Queue với các chức năng

In [88]:
class MyQueue:
  def __init__(self,capacity):
    self.__capacity=capacity
    self.__queue=[]
  def is_empty(self):
    return len(self.__queue)==0
  def is_full(self):
    return len(self.__queue)==self.__capacity
  def enqueue(self,value):
    if self.is_full():
      raise Exception("Queue is full")
    else:
      self.__queue.append(value)
  def dequeue(self):
    if self.is_empty():
      raise Exception("Queue is empty")
    else:
      return self.__queue.pop(0)

In [90]:
my_queue=MyQueue(5)
my_queue.is_empty()
my_queue.enqueue(1)
my_queue.enqueue(2)
my_queue.enqueue(3)
my_queue.enqueue(4)
my_queue.enqueue(5)

In [93]:
my_queue.enqueue(6)

In [92]:
my_queue.dequeue()

1