<a href="https://colab.research.google.com/github/hungpx2008/AIO-Exercise/blob/Feature%2FExercise-activate-funtion/Module_02_Vector_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [6]:
vector = np. array ([ -2 , 4 , 9 , 21])
def compute_vector_length (vector):
    return np.sqrt(np.sum(vector**2))
result = compute_vector_length (vector )
print ( round (result ,2) )

23.28


In [7]:
v1 = np. array ([0 , 1 , -1 , 2])
v2 = np. array ([2 , 5 , 1 , 0])
def compute_dot_product (v1 , v2):
    return np.sum(v1*v2)
result = compute_dot_product (v1 , v2)
print ( round (result ,2) )

4


In [9]:
x = np. array ([[1 , 2] ,[3 , 4]])
k = np. array ([1 , 2])
print ('result \n', k.dot (x) )

result 
 [ 7 10]


In [11]:
x = np. array ([[ -1 , 2] ,[3 , -4]])
k = np. array ([1 , 2])
print ('result \n', k@x )

result 
 [ 5 -6]


In [12]:
m = np. array ([[ -1 , 1 , 1] , [0 , -4 , 9]])
v = np. array ([0 , 2 , 1])
def matrix_multi_vector (m , v):
    return m@v
result = matrix_multi_vector(m, v)
print ( result )

[3 1]


In [13]:
m1 = np. array ([[0 , 1 , 2] , [2 , -3 , 1]])
m2 = np. array ([[1 , -3] ,[6 , 1] , [0 , -1]])
def matrix_multi_matrix (m1 , m2):
    return m1@m2
result = matrix_multi_matrix (m1 , m2)
print ( result )

[[  6  -1]
 [-16 -10]]


In [16]:
m1 = np.eye (3)
print(m1)
m2 = np. array ([[1 , 1 , 1] ,[2 , 2 , 2] , [3 , 3 , 3]])
result = m1@m2
print ( result )

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [18]:
m1 = np.eye (2)
m1 = np. reshape (m1 ,( -1 ,4) ) [0]
print('m1',m1)
m2 = np. array ([[1 , 1 , 1 , 1] ,[2 , 2 , 2 , 2] , [3 , 3 , 3 , 3] , [4 , 4 , 4 , 4]])
result = m1@m2
print ( result )

m1 [1. 0. 0. 1.]
[5. 5. 5. 5.]


In [19]:
m1 = np. array ([[1 , 2] , [3 , 4]])
m1 = np. reshape (m1 ,( -1 ,4) , "F") [0]
m2 = np. array ([[1 , 1 , 1 , 1] ,[2 , 2 , 2 , 2] , [3 , 3 , 3 , 3] , [4 , 4 , 4 , 4]])
result = m1@m2
print ( result )

[29 29 29 29]


In [20]:
m1 = np. array ([[ -2 , 6] , [8 , -4]])
def inverse_matrix (m1):
    return np.linalg.inv(m1)
result = inverse_matrix (m1)
print ( result )

[[0.1  0.15]
 [0.2  0.05]]


In [22]:
matrix = np. array ([[0.9 , 0.2] , [0.1 , 0.8]])
def compute_eigenvalues_eigenvectors (matrix):
    eigenvalues , eigenvectors = np.linalg.eig(matrix)
    return eigenvalues , eigenvectors
eigenvalues , eigenvectors = compute_eigenvalues_eigenvectors ( matrix )
print ( eigenvectors )

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [23]:
x = np. array ([1 , 2 , 3 , 4])
y = np. array ([1 , 0 , 3 , 0])
def compute_cosine (x , y):
    return np.dot(x,y)/(np.linalg.norm(x)*np.linalg.norm(y))
result = compute_cosine (x,y)
print ( round (result , 3) )

0.577
